language: R
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

before_install: |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include";
  fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    Rscript -e "options(install.packages.check.source = 'no'); install.packages('roxygen2', type = 'binary', repos = 'http://cran.rstudio.org')"
  else
    Rscript -e "install.packages('roxygen2', repos = 'http://cran.rstudio.org')"
  fi

after_success:
    - cat "${RCHECK_DIR}/tests/testthat.Rout"
    - Rscript -e 'install.packages("covr"); covr::codecov()'
