name: Tests

on: [push]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            r_version: '3.6.3'
          - os: ubuntu-latest
            r_version: '4.0.3'
          - os: macos-latest
            r_version: '3.6.3'
          - os: macos-latest
            r_version: '4.0.3'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r_version }}
      - name: Setup and run tests
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
              export OS_NAME="macos"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              export OS_NAME="linux"
          fi
          $GITHUB_WORKSPACE/.ci/test.sh
      - name: covr
        shell: bash
        run: |
          cat "pkgnet.Rcheck/tests/testthat.Rout"
          Rscript -e "covr::codecov()"
  # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
