name: Tests

on: [push]

jobs:
  test:
    name: ${{ matrix.os }} (R ${{ matrix.r-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            r-version: '3.6'
          - os: ubuntu-latest
            r-version: 'release'
          - os: macos-latest
            r-version: '3.6'
          - os: macos-latest
            r-version: 'release'
    steps:
      - name: sheckout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: set up dependencies
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
              export OS_NAME="macos"
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              export OS_NAME="linux"
          fi
          $GITHUB_WORKSPACE/.github/setup.sh
      - name: run tests
        shell: bash
        run: |
          $GITHUB_WORKSPACE/test.sh
      - name: upload coverage
        if: ${{ matrix.os == 'macos-latest' && matrix.r-version == 'release' }}
        shell: bash
        run: |
          cat "pkgnet.Rcheck/tests/testthat.Rout"
          Rscript -e "covr::codecov()"
  # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
